# Generated by Django 3.2.13 on 2022-11-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_url', models.TextField()),
                ('goods_img_url', models.TextField()),
                ('goods_brand', models.ForeignKey(db_column='goods_brand', on_delete=django.db.models.deletion.CASCADE, to='articles.brand', to_field='brand')),
                ('goods_category', models.ForeignKey(db_column='goods_category', on_delete=django.db.models.deletion.CASCADE, to='articles.category', to_field='category')),
            ],
        ),
    ]
